sudo: false

language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update

install:
  - (cd api && travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source)
  - (cd api && composer info -i)

script:
  - (cd api && vendor/bin/phpcs)
  - (cd api && vendor/bin/phpunit)
